import {describe,it,expect} from 'vitest';
import {initialState,makeSession,checkSession,nextSession,expected,matches,diffWords,maskIndices,scheduleReview,finishState,validateState,copyCharacters,type Session} from './engine';
const sentence={id:'test',en:'Small steps lead to meaningful progress.',zh:'小步前进。'};
const answer=(s:Session)=>nextSession(checkSession({...s,input:expected(s.tasks[s.index])}));
describe('answer matching',()=>{
  it('ignores case, repeated spaces, punctuation without accepting wrong word order',()=>{expect(matches('Hello, World!','hello   world',false)).toBe(true);expect(matches("I don't know.",'I don’t know',false)).toBe(true);expect(matches('We learn every day.','We every learn day',false)).toBe(false);});
  it('strict mode preserves every character',()=>{expect(matches('Hello.','hello.',true)).toBe(false);expect(matches('Hello.','Hello. ',true)).toBe(false);expect(matches('Hello.','Hello.',true)).toBe(true);});
  it('distinguishes missing, extra and wrong words',()=>{expect(diffWords('We learn every day','We learn day').some(d=>d.kind==='missing'&&d.expected==='every')).toBe(true);expect(diffWords('We learn','We really learn').some(d=>d.kind==='extra'&&d.actual==='really')).toBe(true);expect(diffWords('We learn','We teach').some(d=>d.kind==='wrong')).toBe(true);});
  it('live feedback tolerates punctuation but catches incorrect letters',()=>{expect(copyCharacters('Hello, world!','hello world',false).some(c=>c.status==='mistyped')).toBe(false);expect(copyCharacters('Hello','Hallo',false).some(c=>c.status==='mistyped')).toBe(true);});
  it('masks approximately a third of words and keeps sentence order',()=>{expect(maskIndices(sentence.en)).toHaveLength(2);expect(maskIndices('Go!')).toEqual([0]);expect(maskIndices(sentence.en)).toEqual([...maskIndices(sentence.en)].sort((a,b)=>a-b));});
});
describe('whole-group learning',()=>{
  it('runs whole groups through copy, cloze, recall in order',()=>{const s=makeSession('test',[sentence,{...sentence,id:'second'}],false);expect(s.tasks.map(t=>t.phase)).toEqual(['copy','copy','cloze','cloze','recall','recall']);});
  it('requires explicit advance and does not advance after a wrong answer',()=>{const s=makeSession('test',[sentence],false);const checked=checkSession({...s,input:sentence.en});expect(checked.index).toBe(0);expect(nextSession({...checked,checked:false}).index).toBe(0);expect(nextSession(checked).index).toBe(1);});
  it('finishes a clean three-stage session and schedules one day later',()=>{let s=makeSession('test',[sentence],false);while(!s.complete)s=answer(s);expect(s.tasks).toHaveLength(3);expect(s.results.test.independent).toBe(true);const state=finishState(initialState(),s);expect(state.reviews.test.step).toBe(0);expect(state.reviews.test.needsReview).toBe(false);expect(finishState(state,s).history).toHaveLength(1);});
  it('appends each difficult sentence once, without an infinite retry loop',()=>{let s=makeSession('test',[sentence],false,true);s={...s,currentHelp:true,hint:3};s=answer(s);expect(s.tasks).toHaveLength(2);expect(s.tasks[1].retry).toBe(true);expect(s.results.test.independent).toBe(false);s=answer({...s,currentHelp:true});expect(s.complete).toBe(true);expect(s.tasks).toHaveLength(2);expect(finishState(initialState(),s).reviews.test.needsReview).toBe(true);});
  it('remembers errors even after correction; a clean retry resets interval',()=>{let s=makeSession('test',[sentence],false,true);s=checkSession({...s,input:'incorrect'});s=answer(s);expect(s.results.test.error).toBe(true);expect(s.results.test.independent).toBe(false);s=answer(s);const state=initialState();state.reviews.test={step:2,due:new Date().toISOString(),lastPracticed:new Date().toISOString(),needsReview:false};expect(finishState(state,s).reviews.test.step).toBe(0);});
});
describe('review calendar',()=>{
  it('advances 1, 3, 7 days using calendar days across month boundaries',()=>{const now=new Date('2026-01-31T12:00:00');let r=scheduleReview(undefined,true,false,now);expect(new Date(r.due).getDate()).toBe(1);r=scheduleReview(r,true,false,now);expect(new Date(r.due).getDate()).toBe(3);r=scheduleReview(r,true,false,now);expect(new Date(r.due).getDate()).toBe(7);expect(r.step).toBe(2);});
  it('failed review becomes due now, then restarts at one day',()=>{const now=new Date();const failed=scheduleReview(undefined,false,true,now);expect(failed.due).toBe(now.toISOString());expect(scheduleReview(failed,true,false,now).step).toBe(0);});
});
describe('portable records',()=>{
  it('round-trips settings, content, in-progress input and dates',()=>{const s=initialState();s.session=makeSession('test',s.decks[0].sentences,false);s.session.input='Small st';expect(validateState(JSON.parse(JSON.stringify(s)))).toEqual(s);});
  it('rejects invalid versions, duplicate ids, broken positions and review dates',()=>{expect(()=>validateState({...initialState(),version:2})).toThrow();const dupe=initialState();dupe.decks[0].sentences.push(dupe.decks[0].sentences[0]);expect(()=>validateState(dupe)).toThrow();const broken=initialState();broken.session=makeSession('test',broken.decks[0].sentences,false);broken.session.index=999;expect(()=>validateState(broken)).toThrow();const date=initialState();date.reviews['sample-1']={step:0,due:'invalid',lastPracticed:new Date().toISOString(),needsReview:false};expect(()=>validateState(date)).toThrow();});
});
